### ISSUE TITLE
Component type "executable" or "exe"?

### ISSUE THREAD

**Issue by memsharded** [cps-org/cps#69]
The sample uses "exe" in https://cps-org.github.io/cps/sample.html, but https://cps-org.github.io/cps/schema.html#type says "executable".

Which one is the correct one? I can do a PR to change it.

**Comment by alexreinking** [comment]
I would _want_ it to be "executable" as "exe" reads strongly Windows-specific. I am not an authority on this matter, however.

**Comment by mwoehlke** [comment]
Pretty sure the sample is wrong :flushed:... thanks for noticing! The only [`type`](https://cps-org.github.io/cps/schema.html#type)s that are abbreviated are `dylib` and `jar`, largely because `dynamic_library` and `java_archive` are getting obnoxiously long. :slightly_smiling_face: (Also, `jar` is a canonical extension... although if we ever wind up with e.g. `<lang>_module` for non-CABI stuff, I may consider `java_archive`...)
