### ISSUE TITLE
"semver" should actually mean "semver"

### ISSUE THREAD

**Issue by dcbaker** [cps-org/cps#7]
This spec uses "semver" to mean something other than semantic versioning, that's not nice. If i say "semver" I expect that the comparability will be calculated using semver semantics, not something else. This really feels like porting the cmake-configism over, and this is not the way pkg-config or well behaved backwards compatible projects work, I'm not opposed to having the "Compat-Version" field, but I'd propose something like:

Adding "x.y.z" in addition to "semver", "x.y.z" gets the same sorting logic as semver, but keeps the "Compat-Version" logic that "semver" currently implements, while "semver" means "semantic versioning" and uses the semantic versioning logic, while using "semver" and "Compat-Version" together is not allowed.

**Comment by mwoehlke** [comment]
`semver` (in the [`Version-Schema`](https://cps-org.github.io/cps/schema.html#version-schema) context) is only a way of specifying how to *parse* the version number. What CPS implements is a superset of semver. In fact, it's something of a misnomer here, because what it really means (or is intended to mean, at least) is that the version number looks like:

```
version-number:
  integer
  integer . version-number

integer:
  [0-9]
  [1-9] integer
```

...where each subsequent integer has less "influence" on the version number. "semver" is maybe not ideal to express this, but I don't have a better name offhand. If you have a suggestion, please share!

Many, many packages are going to conform to that scheme, but many *won't* follow the *semantics* of semver.

I do want to have *something* that conforms to the above, and not just to a more complicated spec, as the above is easiest to parse and is likely sufficient for many, if not most, users. Eventually, however, I'm almost certain we're going to need to explicitly identify other schemas.

**Comment by mwoehlke** [comment]
The specification clearly states the intent, which is that [`Version-Schema`](https://cps-org.github.io/cps/schema.html#version-schema) specifies only *syntax*, not *semantics*, and I stand behind the reason for that as expressed in the previous comment.

As also noted, I'm open to alternate suggestions for how to name the *syntax* in question. Absent such suggestions, however, I'm closing this as WONTFIX.

**Comment by dcbaker** [comment]
Sorry, I've been on a personal leave for the last month or so I haven't had a chance to respond.

I think the use of "simple" is better than semver, so I guess I consider my actual objection fixed by that deprecation
