### ISSUE TITLE
does cps_path require `@prefix@`, or just recomend it?

### ISSUE THREAD

**Issue by dcbaker** [cps-org/cps#75]
The description for the `cps_path` attribute says the following:
```txt
Specifies the directory portion location of the .cps file.
This shall be an “absolute” path which starts with @prefix@.
```

Does this mean that a well formed file *must* have `@prefix@` as the root of this attribute, or that it *may* have this?

A particular case I'm thinking about is providing cps configuration files on the side of official packages, such that you have the following layout:
```
/usr/lib/*
/usr/include/*
~/cps-files/*
```
where the cps-files are not in the same prefix as the system provided packages, but are provided for them.

**Comment by mwoehlke** [comment]
`cps_path` **must** start with `@prefix@`; this is required for the attribute to be meaningful. Note, however, that `cps_path` itself is *not* required.

A tool consuming a `.cps` file knows the absolute location of the file, but *doesn't* necessarily know what prefix that file lives in. (Consider e.g. if a user points at a specific `.cps` file not in a standard prefix.) When `cps_path` is provided, the prefix is determined by removing common suffixes from the `cps_path` and the real path of the `.cps` file. This process *should* result in just `@prefix@` on one side, and the real prefix path on the other. (If it doesn't, the tool is expected to be noisily unhappy. :slightly_smiling_face:) Naturally, this only works if `cps_path` starts with `@prefix@`.

In a recent conversation, if I understood correctly, @bretbrownjr was talking about this same (or very similar) layout and how to support it. Really, I see only three options:

1. Allow the `.cps` file to specify `@prefix@` directly.
2. Allow the *consumer* to specify the prefix, independent of the `.cps` file location.
3. Don't use `@prefix@` in the `.cps` file. (And don't provide `cps_path`.)

Now, (1) effectively makes the package not relocatable. It's also silly; all you've done compared to (3) is saved a few bytes on disk at the cost of making the specification more complicated and creating extra work for consuming tools. (2) adds (human) *user* complexity for questionable benefit. Both (1) and (2) also require specification changes. (3) works right now. (Note also that CMake build-tree `.cps` files will do (3) whenever they get implemented.)

Since you don't seem to be asking for (2), I think (3) is the path that makes the most sense for your example.

Related, this does imply that tools should gracefully handle not knowing the prefix if the `.cps` file never actually use `@prefix@`.

Again, you aren't *required* to use `@prefix@` to specify locations in a `.cps`; absolute paths are perfectly valid. The purpose of `@prefix@` is to allow packages to be relocatable; that is, to pick up all their files and transplant them to a different prefix without needing to change the `.cps` file. Relocatability may be desirable, but it is *not* required. (In particular, it's helpful for building distro packages, which get "installed" to `$BUILDROOT`, but are intended to be installed to `/usr` in actual use.) If the `.cps` file doesn't share a reasonable prefix with the rest of the package (as in your side-loading example), you're going to have a hard time keeping relocatability. In those cases, and especially when providing a `.cps` file for distro packages that almost certainly aren't going to be "relocated" *anyway*, it's almost certainly easiest to simply not worry about relocatability and just use absolute paths.

**Comment by dcbaker** [comment]
I think I have my answer, thanks!
